### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by birama** [openpetra/openpetra#144]
I have started the french translation here https://weblate.openpetra.org/projects/openpetra/openpetra/fr/ 
Can you  validate it and  integrate it in the next release ?

**Comment by tpokorra** [comment]
Thank you @birama! Welcome to the OpenPetra project, and thank you for the effort you are putting in!

My french is quite rusty, and I don't have currently time to review the translation properly. But I trust that you know what you are doing :)

I hope that the nightly build of the standalone will contain the french translation tomorrow: https://lbs.solidcharity.com/package/tpokorra/openpetra/openpetranow-standalone-nightly

Please can you share on the forum how you are using OpenPetra, or how you are planning to use it? https://forum.openpetra.org/c/developer-area/people

I hope to catch up with the ICT branch of OpenPetra (merging the branches), and have another beta release within the next month or so.
