### ISSUE TITLE
Logging Windows Client: rotate the client log file

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#19]
Remote client:
The file C:\Users\tpokorra\AppData\Roaming\OpenPetraNazareth\tmp30\PetraClient.log will grow in size and is currently never reset.

This is the same in the development environment with \log\PetraClient.log, and WebServer.log etc.

I think it is best to fix it for all logging files.

Proposal: modify the constructor of TLogWriter
https://github.com/openpetra/openpetra/blob/master/csharp/ICT/Common/LogWriter.cs#L96
to check for the last write access (FileSystemInfo.LastWriteTime)
If the file has been changed today, do nothing.
Otherwise rotate the files similar to logrotate:
eg the current log file for today is PetraClient.log, the logfile from yesterday PetraClient-1.log, the day before yesterday PetraClient-02.log, and files older than 6 days are deleted.

**Comment by Jonischkeit** [comment]
Done, cheked in into my repo (branchSimon)

**Comment by tpokorra** [comment]
I have merged the pull request now, and run nant uncrustify on it, and fixed a couple of typos.
see https://github.com/openpetra/openpetra/pull/26, which I have also just applied.

Thank you Simon!
