### ISSUE TITLE
make sure that GL Batches can only be modified if they are UNPOSTED

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#255]
similar to gift batches

**Comment by The-CJ** [comment]
see fixes in js client
https://github.com/openpetra/openpetra-client-js/tree/fix_CJ_20181029

**Comment by tpokorra** [comment]
we can also disable the submit and delete button on the transaction edit dialog

**Comment by tpokorra** [comment]
transaction edit dialog should be readonly
