### ISSUE TITLE
Posting a Gift Batch closes the Batch but returns an Error and notice to the Server logs

### ISSUE THREAD

**Issue by The-CJ** [openpetra/openpetra#263]
AGiftBatchNumber
ALedgerNumber
<< serverMFinance.asmx/TGiftTransactionWebConnector_PostGiftBatch

>> {"Message":"Please check server log file","StackTrace":"  at Ict.Petra.Server.App.WebService.TMFinanceWebService.TGiftTransactionWebConnector_PostGiftBatch (System.Int32 ALedgerNumber, System.Int32 AGiftBatchNumber) [0x0008c] in \u003ce7327d206f0a410ead4958c32a04774d\u003e:0 \n  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)\n  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in \u003c6f4fee1d52c14c268f9079127f87fd0f\u003e:0 ","ExceptionType":"System.Exception"}

**Comment by tpokorra** [comment]
seems to have been fixed already before
