### ISSUE TITLE
Adding/Editing a Gift Transaction Detail fails

### ISSUE THREAD

**Issue by The-CJ** [openpetra/openpetra#264]
ABatchNumber
ADetailNumber
AGiftCommentOne
AGiftTransactionAmount
AGiftTransactionNumber
ALedgerNumber
AMotivationDetailCode
AMotivationGroupCode
DateEntered
action
<< serverMFinance.asmx/TGiftTransactionWebConnector_MaintainGiftDetails

-> {"d":"{\"AVerificationResult\": [],\"result\": false}"}

**Comment by tpokorra** [comment]
is now fixed
