### ISSUE TITLE
Creating a new Gift Batch, creates it, but throws an error

### ISSUE THREAD

**Issue by The-CJ** [openpetra/openpetra#266]
AAccountName
ABankAccountCode
ABankCostCentre
ABatchDescription
ABatchNumber
ABatchStatus
ACostCenterName
AGlEffectiveDate
ALedgerNumber
action
<< serverMFinance.asmx/TGiftTransactionWebConnector_MaintainBatches

-> {"d":"{\"AVerificationResult\": [],\"result\": false}"}

**Comment by tpokorra** [comment]
cannot reproduce this anymore
