### ISSUE TITLE
Recurring Gift Batches for member fees

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#351]
some charities have members, that pay a regular amount each month. We can do this via recurring gift batches with the option of SEPA direct debit, but it is not implemented in the javascript client yet, only on the server.

**Comment by tpokorra** [comment]
Implementation: Very similar to GiftBatches.html and GiftBatches.js in https://github.com/openpetra/openpetra/tree/master/js-client/src/forms/Finance/Gift/GiftEntry: Copy both files to RecurringGiftBatches.html and RecurringGiftBatches.js

The server functions are very similar as well, see https://demo.openpetra.org/api/serverMFinance.asmx, eg. TGiftTransactionWebConnector_LoadARecurringGiftBatch for loading all recurring gift batches (we don't need filtering, because there will be only max. 5 recurring gift batches).
TGiftTransactionWebConnector_LoadRecurringGiftTransactionsForBatch for loading the transactions of a recurring gift batch.
We need to implement TGiftTransactionWebConnector_MaintainRecurringBatches, TGiftTransactionWebConnector_MaintainRecurringGifts and TGiftTransactionWebConnector_MaintainRecurringGiftDetails on the server side.

**Comment by tpokorra** [comment]
There is no Post function, but Submit Function: TGiftTransactionWebConnector_SubmitRecurringGiftBatch, that creates a normal gift batch which can be posted.

The SEPA Export is also triggered from the recurring gift batches form, but needs to be implemented on the server side first. We have https://github.com/SolidCharity/OpenPetraPlugin_SEPA which needs to be merged into the OpenPetra server code.

**Comment by tpokorra** [comment]
@The-CJ: 
Please merge from openpetra/dev branch.

then run these commands:

```
nant compileProject -D:name=Ict.Petra.Server.lib.MFinance.Gift
nant generateGlue
nant quickCompile -D:onlyonce=true
```
I have added the date parameters AStartDonations and AEndDonations to MaintainRecurringGiftDetails. We need to see if AEndDonations is processed correctly if it is null, which it should be allowed to be.

TODO @tpokorra: SEPAMandate and IBAN need to be added to the Load methods...
I still need to figure out

**Comment by The-CJ** [comment]
Missing Keys:
- DonorName (or familiar)

in TGiftTransactionWebConnector_LoadRecurringGiftTransactionsForBatch

**Comment by tpokorra** [comment]
Please `git pull` from DEV branch and run:

```
nant generateORM quickCompile -D:onlyonce=true
nant compileProject -D:name=Ict.Petra.Server.lib.MFinance.Gift
```
TODO: when displaying the recurring batch with transactions, I get now this error on the javascript console: `TypeError: undefined currency in NumberFormat() with currency style`

TODO: add date fields for AStartDonations and AEndDonations to the html and js, replace hardcoded dates. AEndDonations can be null

**Comment by The-CJ** [comment]
More missing values in API:

GET TGiftTransactionWebConnector_LoadRecurringGiftTransactionsForBatch

Keys:
ACurrencyCode : for currency format

**Comment by tpokorra** [comment]
At the moment, it is disabled in the UI, it can be enabled by uncommenting RecurringGiftBatches in https://github.com/openpetra/openpetra/blob/master/js-client/etc/UINavigation.yml#L54

**Comment by tpokorra** [comment]
this has now been implemented
