### ISSUE TITLE
GL Batch: Import and Export of transactions

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#378]
need to add a howto: GLBatches.message_import_howto.
Need to test it.
Add to manual as well.

**Comment by samlemonsam** [comment]
can you elaborate on this issue some more? Sounds interesting but not sure what to do or where to start.

**Comment by samlemonsam** [comment]
?

**Comment by tpokorra** [comment]
Sorry, quite busy with other things at the moment. The task of this issue is, to check if it is working, and to document it. So I guess I should assign that to myself, and just get it done! I have tried to avoid this ticket for too long...
