### ISSUE TITLE
translation missing for LedgerSetup.entry_first_current_period

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#382]
should also fix the screenshot in the manual

**Comment by tpokorra** [comment]
needs to be fixed in https://github.com/openpetra/openpetra/blob/master/js-client/locales/en/common.json#L366

and in the manual, replace the screenshot: https://github.com/openpetra/openpetra-docs/blob/master/source/howtos/images/add_ledger.png

**Comment by samlemonsam** [comment]
What should we have it say instead of LedgerSetup.entry_first_current_period? "start current period:", "select current period:"?

**Comment by tpokorra** [comment]
"first current period"

**Comment by WilliamsAJ** [comment]
We have a fix from looking at the code, but are not sure of the best way to get a build environment going to take the screenshot. What is the most up-to-date way to get started? I'm sorry if this is supposed to be somewhere else.

**Comment by tpokorra** [comment]
@WilliamsAJ to get a working environment, try https://getopenpetra.com. 

```
curl https://getopenpetra.com | bash -s devenv
```
