### ISSUE TITLE
broken label for title of page MaintainUsers

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#385]
see https://demo.openpetra.org/SystemManager/MaintainUsers

it says: OpenPetra: navigation.MaintainUsers_label

**Comment by PublicFedorenko** [comment]
I can't seem to reproduce this issue. Can you give more information, please?

**Comment by tpokorra** [comment]
sorry, it seems this issue got resolved a while ago.
It was about the title of the page, in the webbrowser title bar.
