### ISSUE TITLE
Server allowed creation of future transactions over max time  

### ISSUE THREAD

**Issue by The-CJ** [openpetra/openpetra#412]
POST /api/serverMFinance.asmx/TGLTransactionWebConnector_MaintainTransactions

Values:
AAccountCode: "0100"
AAccountName: "0100Support Gifts: Local"
AAmountInBaseCurrency: 400
AAmountInIntlCurrency: 0
ABatchNumber: "189"
ACostCenterName: "0400International Clearing House"
ACostCentreCode: "0400"
ACreditAmountBase: "800"
ADebitAmountBase: "400"
ADebitCreditIndicator: false
AJournalNumber: 1
ALedgerNumber: "43"
ANarrative: "Something"
AReference: "DONATION"
ATransactionDate: "2025-12-05"
ATransactionNumber: "4"
action: "create"

Expected behavior: block transaction from creation since the batch is for Dez-2019, but Transaction for Dez-2025
In Reality: Server created trans. anyways

NOTE:
Got blocked first, but stopped sending errors after some tryes... seems like i can brute force transactions... if you know what  i mean

**Comment by tpokorra** [comment]
We cannot reproduce #410 anymore.
Checking for the batch period when saving transaction is quite difficult, because the dataset does not contain the batch anymore, if it is not being changed.
It seems the user has to rely on the validation before posting for the moment.
