### ISSUE TITLE
Support for GDPR / DSGVO

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#433]
data protection: we need to save with each address and contact detail (phone number, email address), the following the details:

* when did the person consent to this?
* how did we get the consent? (phone, email, conversation)
* what can we use the details for? or perhaps not?

consent can be withdrawn.

**Comment by tpokorra** [comment]
same for subscriptions

**Comment by tpokorra** [comment]
we need to consider the permissions in the report for sending publications Partner/Reports/PartnerReports/AnnualReportWithoutAnnualReceiptRecipients

**Comment by tpokorra** [comment]
consider flag no_solicitations: https://dbdoc.openpetra.org/index.html?table=p_partner&group=partner#p_no_solicitations_l
Should we disable that? there is no need for that anymore? Migrate data?

**Comment by The-CJ** [comment]
While writing a test unit for this, it seems like i have run into a problem
See #480

**Comment by tpokorra** [comment]
implemented in https://github.com/openpetra/openpetra/pull/483
