### ISSUE TITLE
provide a weblate instance for translation

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#447]
update the wiki etc.

**Comment by comradekingu** [comment]
Could use Hosted Weblate https://weblate.org/hosting/ :)

**Comment by tpokorra** [comment]
@comradekingu I have now used the hosted weblate, thanks for the pointer :)

https://hosted.weblate.org/projects/openpetra/js-client/

I am still figuring out things, how to push back to the github repo, etc.

I am happy to add you as translator.

**Comment by comradekingu** [comment]
@tpokorra Project removed for the time being, but saw some activity beforehand. Will get to it when I see it up. :)

**Comment by tpokorra** [comment]
first pull request has been merged from Weblate into the test branch: #466
So this looks like it is working

**Comment by comradekingu** [comment]
The actual https://hosted.weblate.org/projects/openpetra/ is not up.

**Comment by tpokorra** [comment]
Thanks for reporting that! It is fixed now.

**Comment by comradekingu** [comment]
@tpokorra I am seeing https://hosted.weblate.org/engage/openpetra/
but not https://hosted.weblate.org/projects/openpetra/ …?

**Comment by tpokorra** [comment]
@comradekingu 
Even if I try as an anonymous user, I can see https://hosted.weblate.org/projects/openpetra/js-client/
Do you have a registered user, and are you logged in to weblate? Do I need to add your user first to the openpetra project? What is your username at Weblate? Or send me a private e-mail to info -at- openpetra.org

**Comment by comradekingu** [comment]
@tpokorra I think you may have made it private, maybe you see it because you are the admin?
If not inadvertently so, could you add "kingu" as a user?

**Comment by tpokorra** [comment]
sorry, somehow I forgot about this ticket. 
I have made the project on Weblate now public, so there is no issue for adding users anymore.
