### ISSUE TITLE
Migrate data for new way of dealing with consent for partner data

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#486]
related to #433 
Demo Database with Consent. Update Tests for Reports.
Upgrade existing database, add consent?

**Comment by The-CJ** [comment]
see e0c665bcebf569d63597ad50dda8d626b47428ca

**Comment by tpokorra** [comment]
there are still issues with an upgraded database: trying to change an existing address, that will lead to "consent_error"

**Comment by tpokorra** [comment]
has been fixed
