### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by Lukas2112** [openpetra/openpetra#621]
Would a Mastodon account for the project be possible?

**Comment by Lukas2112** [comment]
I would like to offer my support for the operation of an OpenPetra-Mastodon account.

**Comment by tpokorra** [comment]
which Mastodon instance would you recommend?
I have already played around with setting up my own instance, at solidcharity.net.
The ansible script: https://github.com/tpokorra/Hostsharing-Ansible-Mastodon
Perhaps also a PeerTube instance for training videos.

**Comment by Lukas2112** [comment]
I could imagine ``social.tchncs.de`` as a potential Mastodon instance and perhaps ``tube.tchncs.de`` as a PeerTube instance - would have the advantage that administration of a separate instance would not necessarily be necessary.

**Comment by tpokorra** [comment]
I have now setup my own Mastodon instance solidcharity.net
We now have a german and an english account:

https://solidcharity.net/@openpetra
https://solidcharity.net/@openpetra_de
