### ISSUE TITLE
Local integration of the font on https://www.openpetra.com/ 

### ISSUE THREAD

**Issue by Lukas2112** [openpetra/openpetra#650]
Currently, according to uBlock Origin in my firefox, Google Font is included. 

This does not seem to me to be compatible with the GDPR. 

A local integration of the font could solve the problem.

**Comment by tpokorra** [comment]
This is not related to OpenPetra.org, so I will close this issue.
But thanks for the hint.
I will follow https://www.webtimiser.de/webfonts-lokal-in-wordpress/ to fix the reference to Google in the wordpress theme.
